services:
  jupyterlab:
    container_name: cuda-lib
    user: root
    build: .
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NB_USER=jupyternb
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
    volumes:
      - ../cuda-notebooks:/home/jupyternb
    working_dir: /home/jupyternb
    ports:
      - '8888:8888'
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

