services:
  jupyterlab:
    container_name: jupyter-cuda
    user: root
    image: nvidia/cuda:12.6.2-devel-ubuntu22.04
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_TOKEN=token
      - NB_USER=jupyternb
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
    volumes:
      - ../cuda-notebooks:/home/jupyternb
    working_dir: /home/jupyternb
    ports:
      - "8888:8888"
    command: >
      bash -lc '
        set -e;
        if [ ! -x /venv/bin/python ]; then
          apt-get update &&
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            python3 python3-pip python3-venv && \
          python3 -m venv /venv;
        fi;
        . /venv/bin/activate && \
        python -m pip install --upgrade pip && \
        pip install --no-cache-dir \
          --extra-index-url https://pypi.nvidia.com \
          "cuda-cccl==0.1.3.1.0.dev1678" \
          "cuda-python==12.9.0" \
          cupy-cuda12x \
          numpy jupyterlab && \
        jupyter lab --ip=0.0.0.0 --no-browser --allow-root \
          --ServerApp.token= --ServerApp.password=
      '
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


