services:
  jupyterlab:
    container_name: cuda-lib
    user: root
    image: nvidia/cuda:12.6.2-devel-ubuntu22.04
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../cuda-notebooks:/home/jupyternb
    working_dir: /home/jupyternb
    ports:
      - "8888:8888"
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y python3 python3-pip &&
        pip3 install --upgrade pip &&
        pip3 install jupyterlab &&
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


